namespace YowThi.Erp.Domain.Inventory;

public enum InventoryMovementType
{
    PURCHASE_RECEIPT,
    PROCESS_CONSUME,
    PROCESS_PRODUCE,
    FINAL_PACKAGE_CONSUME,
    FINAL_PACKAGE_PRODUCE,
    OUTSOURCED_RECEIPT,
    TRANSFER_OUT,
    TRANSFER_IN,
    SALES_ISSUE,
    SALES_ALLOCATION_ADJUSTMENT,
    ADJUSTMENT,
    BATCH_RECONCILIATION,
}
