export const inventoryOperationsCopy = {
  'zh-TW': {
    eyebrow: 'P7 · 庫存', title: '庫存移轉／盤整登記',
    intro: '使用正式庫存移轉與盤整操作。移轉登記移出與移入；盤整只登記數量差額與原因。',
    transfer: '庫存移轉', adjustment: '庫存盤整', searchSource: '搜尋品項、來源或位置', searchIdentity: '搜尋盤整品項或來源',
    chooseSource: '選擇來源庫存餘額', chooseIdentity: '選擇庫存品項', destination: '目的儲位', adjustmentLocation: '盤整儲位',
    chooseDestination: '選擇啟用中的目的位置', chooseLocation: '選擇未刪除位置', loading: '載入中…', balance: '目前可用餘額', batchDate: '批次日期',
    origin: '來源', objectKind: '類別', rawSource: '原始來源', sourceLocation: '來源位置', farmersCombined: '農戶合併', supplierSource: '供應商', inHouseOrigin: '內製', outsourcedOrigin: '委外', procurementProductKind: '採購產品', processMaterialKind: '加工物料', salesProductKind: '銷售產品', inactiveStatus: '停用',
    inactiveSource: '來源位置目前停用；系統仍允許將既有庫存移出。',
    inactiveAdjustmentLocation: '此位置目前停用，但尚未刪除，因此仍可用於盤整。',
    quantity: '移轉數量', quantityDelta: '盤整數量差額', reason: '盤整原因／作業情境',
    reasonPlaceholder: '例如：盤點差異、損耗、破損、秤重差異等實際原因',
    deltaHint: '正數增加、負數減少；此欄是數量差額，不是盤點後絕對庫存。',
    submitTransfer: '登記庫存移轉', submitAdjustment: '登記庫存盤整', submitting: '登記中…', required: '請完整選擇本次庫存操作需要的資料。',
    invalidQuantity: '移轉數量必須大於 0。', exceedsBalance: '移轉數量不可超過目前來源可用餘額。', sameLocation: '來源與目的儲位必須不同。',
    invalidDelta: '數量差額必須是非 0 數值。', reasonRequired: '盤整原因必填。', queryFailed: '庫存操作選項查詢失敗',
    invalidInput: '庫存操作資料無效，請重新核對選項與數量。', positionMissing: '來源庫存餘額已不存在或已變更，請重新載入。',
    locationMissing: '儲位已不存在或目前不符合此操作要求，請重新載入。', insufficient: '來源庫存不足，請重新載入最新餘額。',
    batchClosed: '來源批次已關閉、刪除或不可操作。', concurrent: '庫存餘額已被其他操作變更，請重新載入後再登記。',
    idempotency: '此操作識別碼已被不同請求使用，請重新開始一次登記。', unexpected: '發生未預期錯誤。',
    transferSuccess: '庫存移轉已登記', adjustmentSuccess: '庫存盤整已登記', operationId: '庫存操作', movement1: '主要庫存異動', movement2: '移入庫存異動', resultQuantity: '數量／差額',
  },
  'th-TH': {
    eyebrow: 'P7 · สินค้าคงคลัง', title: 'บันทึกการโอน / ปรับปรุงสินค้าคงคลัง',
    intro: 'ใช้การโอนและการปรับปรุงสินค้าคงคลังตามการทำงานจริง การโอนบันทึกทั้งขาออกและขาเข้า ส่วนการปรับปรุงบันทึกผลต่างจำนวนกับเหตุผล',
    transfer: 'โอนสินค้าคงคลัง', adjustment: 'ปรับปรุง / ตรวจนับ', searchSource: 'ค้นหาสินค้า แหล่งที่มา หรือที่เก็บ', searchIdentity: 'ค้นหารายการหรือแหล่งที่มา',
    chooseSource: 'เลือกยอดคงเหลือต้นทาง', chooseIdentity: 'เลือกรายการสินค้าคงคลัง', destination: 'ตำแหน่งจัดเก็บปลายทาง', adjustmentLocation: 'ตำแหน่งจัดเก็บที่ปรับปรุง',
    chooseDestination: 'เลือกปลายทางที่ใช้งาน', chooseLocation: 'เลือกตำแหน่งที่ยังไม่ถูกลบ', loading: 'กำลังโหลด…', balance: 'ยอดคงเหลือปัจจุบัน', batchDate: 'วันที่ล็อต',
    origin: 'แหล่งที่มา', objectKind: 'ประเภท', rawSource: 'แหล่งที่มาดั้งเดิม', sourceLocation: 'ตำแหน่งต้นทาง', farmersCombined: 'เกษตรกรรวม', supplierSource: 'ผู้จำหน่าย', inHouseOrigin: 'ผลิตภายใน', outsourcedOrigin: 'จัดหาภายนอก', procurementProductKind: 'สินค้าจัดซื้อ', processMaterialKind: 'วัตถุดิบแปรรูป', salesProductKind: 'สินค้าขาย', inactiveStatus: 'ไม่ใช้งาน',
    inactiveSource: 'ตำแหน่งต้นทางไม่ใช้งาน แต่ยังสามารถนำสินค้าคงคลังเดิมออกได้',
    inactiveAdjustmentLocation: 'ตำแหน่งนี้ไม่ใช้งานแต่ยังไม่ถูกลบ จึงยังใช้ปรับปรุงได้',
    quantity: 'จำนวนที่โอน', quantityDelta: 'ผลต่างจำนวน', reason: 'เหตุผล / บริบทการปรับปรุง',
    reasonPlaceholder: 'เช่น ผลต่างจากการตรวจนับ สูญเสีย เสียหาย หรือผลต่างจากการชั่ง',
    deltaHint: 'ค่าบวกเพิ่ม ค่าลบลด ช่องนี้เป็นผลต่างจำนวน ไม่ใช่ยอดคงเหลือหลังตรวจนับ',
    submitTransfer: 'บันทึกการโอน', submitAdjustment: 'บันทึกการปรับปรุง', submitting: 'กำลังบันทึก…', required: 'โปรดเลือกรายการที่จำเป็นให้ครบ',
    invalidQuantity: 'จำนวนที่โอนต้องมากกว่า 0', exceedsBalance: 'จำนวนที่โอนต้องไม่เกินยอดคงเหลือปัจจุบัน', sameLocation: 'ตำแหน่งต้นทางและปลายทางต้องต่างกัน',
    invalidDelta: 'ผลต่างจำนวนต้องไม่เท่ากับ 0', reasonRequired: 'ต้องระบุเหตุผลการปรับปรุง', queryFailed: 'โหลดตัวเลือกสินค้าคงคลังไม่สำเร็จ',
    invalidInput: 'ข้อมูลการทำงานสินค้าคงคลังไม่ถูกต้อง', positionMissing: 'ยอดคงเหลือต้นทางไม่มีอยู่หรือเปลี่ยนไปแล้ว โปรดโหลดใหม่',
    locationMissing: 'ตำแหน่งจัดเก็บไม่มีอยู่หรือไม่ตรงเงื่อนไข โปรดโหลดใหม่', insufficient: 'สินค้าคงคลังต้นทางไม่พอ โปรดโหลดยอดล่าสุด',
    batchClosed: 'ล็อตต้นทางปิด ถูกลบ หรือไม่พร้อมใช้งาน', concurrent: 'ยอดคงเหลือถูกเปลี่ยนโดยงานอื่น โปรดโหลดใหม่ก่อนบันทึก',
    idempotency: 'รหัสการทำงานนี้ถูกใช้กับคำขออื่นแล้ว โปรดเริ่มใหม่', unexpected: 'เกิดข้อผิดพลาดที่ไม่คาดคิด',
    transferSuccess: 'บันทึกการโอนแล้ว', adjustmentSuccess: 'บันทึกการปรับปรุงแล้ว', operationId: 'รายการสินค้าคงคลัง', movement1: 'การเคลื่อนไหวหลัก', movement2: 'การเคลื่อนไหวเข้าคลัง', resultQuantity: 'จำนวน / ผลต่าง',
  },
} as const;
