export const inventoryOperationsCopy = {
  'zh-TW': {
    eyebrow: 'P7 · 庫存', title: '庫存移轉 / 盤整登記',
    intro: '直接使用正式 TransferInventory 與 AdjustInventory command。移轉登記 TRANSFER_OUT / TRANSFER_IN；盤整只登記 QuantityDelta + Reason。INV-001 的 absolute / delta UI 尚待確認，因此本階段不做絕對庫存換算。',
    transfer: '庫存移轉', adjustment: '庫存盤整', searchSource: '搜尋品項、來源或位置', searchIdentity: '搜尋盤整品項或來源',
    chooseSource: '選擇來源庫存 Position', chooseIdentity: '選擇 Inventory identity', destination: '目的 Storage Location', adjustmentLocation: '盤整 Storage Location',
    chooseDestination: '選擇 active 目的位置', chooseLocation: '選擇未刪除位置', loading: '載入中…', balance: '目前 Position balance', batchDate: 'Batch date',
    origin: 'Origin', objectKind: 'Object kind', rawSource: 'Raw source', sourceLocation: '來源位置', farmersCombined: '農戶合併',
    inactiveSource: '來源位置目前 inactive；正式 Transfer command 仍允許將既有庫存移出。',
    inactiveAdjustmentLocation: '此位置目前 inactive；正式 AdjustInventory 只要求位置未刪除，因此仍可用於盤整。',
    quantity: '移轉數量', quantityDelta: '盤整 QuantityDelta', reason: '盤整原因 / 作業情境',
    reasonPlaceholder: '例如：盤點差異、損耗、破損、秤重差異等實際原因',
    deltaHint: '正數增加、負數減少；此欄是 ledger delta，不是盤點後絕對庫存。UI 不額外加入「調整後不得為負」限制。',
    submitTransfer: '登記庫存移轉', submitAdjustment: '登記庫存盤整', submitting: '登記中…', required: '請完整選擇本次庫存操作需要的資料。',
    invalidQuantity: '移轉數量必須大於 0。', exceedsBalance: '移轉數量不可超過目前來源 Position balance。', sameLocation: '來源與目的 Storage Location 必須不同。',
    invalidDelta: 'QuantityDelta 必須是非 0 數值。', reasonRequired: 'AdjustInventory 的 Reason 必填。', queryFailed: 'Inventory operation options 查詢失敗',
    invalidInput: '庫存操作資料無效，請重新核對選項與數量。', positionMissing: '來源 Inventory Position 已不存在或已變更，請重新載入。',
    locationMissing: 'Storage Location 已不存在或目前不符合此操作要求，請重新載入。', insufficient: '來源庫存不足，請重新載入最新 balance。',
    batchClosed: '來源 Batch 已關閉、刪除或不可操作。', concurrent: '庫存 Position 已被其他操作變更，請重新載入後再登記。',
    idempotency: '此 Idempotency-Key 已被不同 request 使用，請重新開始一次登記。', unexpected: '發生未預期錯誤。',
    transferSuccess: '庫存移轉已登記', adjustmentSuccess: '庫存盤整已登記', operationId: 'Inventory Operation', movement1: 'Primary Movement', movement2: 'Transfer In Movement', resultQuantity: 'Quantity / Delta',
  },
  'th-TH': {
    eyebrow: 'P7 · สินค้าคงคลัง', title: 'บันทึกการโอน / ปรับปรุงสินค้าคงคลัง',
    intro: 'ใช้ TransferInventory และ AdjustInventory จริง การโอนบันทึก TRANSFER_OUT / TRANSFER_IN ส่วนการปรับปรุงบันทึก QuantityDelta + Reason ขณะนี้ INV-001 เรื่อง absolute / delta UI ยังรอยืนยัน จึงยังไม่แปลงยอด absolute',
    transfer: 'โอนสินค้าคงคลัง', adjustment: 'ปรับปรุง / ตรวจนับ', searchSource: 'ค้นหาสินค้า แหล่งที่มา หรือที่เก็บ', searchIdentity: 'ค้นหารายการหรือแหล่งที่มา',
    chooseSource: 'เลือก Position ต้นทาง', chooseIdentity: 'เลือก Inventory identity', destination: 'Storage Location ปลายทาง', adjustmentLocation: 'Storage Location ที่ปรับปรุง',
    chooseDestination: 'เลือกปลายทาง active', chooseLocation: 'เลือกตำแหน่งที่ยังไม่ถูกลบ', loading: 'กำลังโหลด…', balance: 'Position balance ปัจจุบัน', batchDate: 'Batch date',
    origin: 'Origin', objectKind: 'Object kind', rawSource: 'Raw source', sourceLocation: 'ตำแหน่งต้นทาง', farmersCombined: 'เกษตรกรรวม',
    inactiveSource: 'ตำแหน่งต้นทาง inactive แต่ Transfer command จริงยังอนุญาตให้นำสต็อกเดิมออกได้',
    inactiveAdjustmentLocation: 'ตำแหน่งนี้ inactive แต่ AdjustInventory จริงกำหนดเพียงว่ายังไม่ถูกลบ จึงยังใช้ปรับปรุงได้',
    quantity: 'จำนวนที่โอน', quantityDelta: 'QuantityDelta ที่ปรับปรุง', reason: 'เหตุผล / บริบทการปรับปรุง',
    reasonPlaceholder: 'เช่น ผลต่างจากการตรวจนับ สูญเสีย เสียหาย หรือผลต่างจากการชั่ง',
    deltaHint: 'ค่าบวกเพิ่ม ค่าลบลด ช่องนี้คือ ledger delta ไม่ใช่ยอด absolute และ UI จะไม่เพิ่มข้อห้ามเรื่องยอดติดลบเอง',
    submitTransfer: 'บันทึกการโอน', submitAdjustment: 'บันทึกการปรับปรุง', submitting: 'กำลังบันทึก…', required: 'โปรดเลือกรายการที่จำเป็นให้ครบ',
    invalidQuantity: 'จำนวนที่โอนต้องมากกว่า 0', exceedsBalance: 'จำนวนที่โอนต้องไม่เกิน Position balance ปัจจุบัน', sameLocation: 'Storage Location ต้นทางและปลายทางต้องต่างกัน',
    invalidDelta: 'QuantityDelta ต้องไม่เท่ากับ 0', reasonRequired: 'AdjustInventory ต้องมี Reason', queryFailed: 'โหลด Inventory operation options ไม่สำเร็จ',
    invalidInput: 'ข้อมูลการทำงานสินค้าคงคลังไม่ถูกต้อง', positionMissing: 'Inventory Position ต้นทางไม่มีอยู่หรือเปลี่ยนไปแล้ว โปรดโหลดใหม่',
    locationMissing: 'Storage Location ไม่มีอยู่หรือไม่ตรงเงื่อนไข โปรดโหลดใหม่', insufficient: 'สินค้าคงคลังต้นทางไม่พอ โปรดโหลด balance ล่าสุด',
    batchClosed: 'Batch ต้นทางปิด ถูกลบ หรือไม่พร้อมใช้งาน', concurrent: 'Inventory Position ถูกเปลี่ยนโดยงานอื่น โปรดโหลดใหม่ก่อนบันทึก',
    idempotency: 'Idempotency-Key นี้ถูกใช้กับ request อื่นแล้ว โปรดเริ่มใหม่', unexpected: 'เกิดข้อผิดพลาดที่ไม่คาดคิด',
    transferSuccess: 'บันทึกการโอนแล้ว', adjustmentSuccess: 'บันทึกการปรับปรุงแล้ว', operationId: 'Inventory Operation', movement1: 'Primary Movement', movement2: 'Transfer In Movement', resultQuantity: 'Quantity / Delta',
  },
} as const;
