export const hardDeleteCopy = {
  'zh-TW': {
    eyebrow: 'P7 · Data Protection',
    title: 'Hard Delete 資料保護控制',
    intro: '此頁只提供已正式完成的 Supplier、Customer、Outsourced Vendor、Farmer Hard Delete。Hard Delete 是最高權限、永久實體刪除；成功後不能 Restore。是否可刪除只由 server transaction 內的 target-specific dependency check 與 row_version 判定。',
    suppliers: 'Supplier',
    customers: 'Customer',
    'outsourced-vendors': 'Outsourced Vendor',
    farmers: 'Farmer',
    search: '搜尋名稱',
    choose: '選擇 Hard Delete target',
    loading: '載入中…',
    activeLabel: 'Active state',
    active: 'Active',
    inactive: 'Inactive',
    lifecycleState: 'Lifecycle state',
    current: 'Current',
    deleted: 'Soft deleted',
    rowVersion: 'Row version',
    deletedAt: 'Deleted at',
    notDeleted: '—',
    dependencyGate: 'Dependency gate',
    dependencySupplier: '任何 Procurement Entry、Processing Execution、Inventory Movement、Inventory Position 或 Finance Payable reference 都會阻擋 Hard Delete。',
    dependencyCustomer: '任何 Sales reference 都會阻擋 Hard Delete。',
    dependencyVendor: '任何 Outsourced Supply Batch reference 都會阻擋 Hard Delete，不論 Batch lifecycle 狀態。',
    dependencyFarmer: '任何 Procurement Entry 或 Finance Payable reference 都會阻擋 Hard Delete；不解讀 payment 或 Batch state。',
    irreversible: '永久刪除、不可 Restore',
    confirmation: '我確認這是永久 Hard Delete；我了解成功後 target row 會實體刪除，且只保留 Hard Delete Audit。',
    hardDelete: 'Hard Delete',
    submitting: '永久刪除中…',
    noSelection: '請先選擇 Hard Delete target。',
    confirmationRequired: '必須先確認永久刪除警告。',
    boundaryHint: 'UI 不預測 target 是否可刪除，也不 cascade、detach 或改寫歷史。送出後 server 會鎖定 target、核對 exact row_version、重新檢查 typed dependencies；有依賴就拒絕。',
    queryFailed: 'Hard Delete target options 查詢失敗',
    invalid: 'Hard Delete request 無效，請重新載入後再操作。',
    notFound: '所選 target 已不存在，請重新載入。',
    dependencyBlocked: 'Hard Delete 被 typed dependency 阻擋；系統不會 cascade、detach 或刪除歷史資料。',
    stale: 'Row version 已變更，請重新載入最新狀態後再操作。',
    idempotency: '此 Idempotency-Key 已被不同 request 使用，請重新開始一次操作。',
    unexpected: '發生未預期錯誤。',
    success: 'Hard Delete 已完成',
    deletedTarget: 'Deleted target',
  },
  'th-TH': {
    eyebrow: 'P7 · Data Protection',
    title: 'การควบคุม Hard Delete เพื่อปกป้องข้อมูล',
    intro: 'หน้านี้รองรับเฉพาะ Hard Delete ที่ยืนยันแล้วสำหรับ Supplier, Customer, Outsourced Vendor และ Farmer เท่านั้น Hard Delete เป็นการลบจริงแบบถาวรภายใต้สิทธิ์สูงสุด และ Restore ไม่ได้หลังสำเร็จ ความปลอดภัยตัดสินโดย target-specific dependency check และ row_version ภายใน transaction ของ server เท่านั้น',
    suppliers: 'Supplier',
    customers: 'Customer',
    'outsourced-vendors': 'Outsourced Vendor',
    farmers: 'Farmer',
    search: 'ค้นหาชื่อ',
    choose: 'เลือก Hard Delete target',
    loading: 'กำลังโหลด…',
    activeLabel: 'Active state',
    active: 'Active',
    inactive: 'Inactive',
    lifecycleState: 'Lifecycle state',
    current: 'Current',
    deleted: 'Soft deleted',
    rowVersion: 'Row version',
    deletedAt: 'Deleted at',
    notDeleted: '—',
    dependencyGate: 'Dependency gate',
    dependencySupplier: 'Procurement Entry, Processing Execution, Inventory Movement, Inventory Position หรือ Finance Payable ที่อ้างถึง Supplier จะบล็อก Hard Delete',
    dependencyCustomer: 'Sales ที่อ้างถึง Customer จะบล็อก Hard Delete',
    dependencyVendor: 'Outsourced Supply Batch ที่อ้างถึง Vendor จะบล็อก Hard Delete ไม่ว่า Batch จะอยู่ lifecycle state ใด',
    dependencyFarmer: 'Procurement Entry หรือ Finance Payable ที่อ้างถึง Farmer จะบล็อก Hard Delete โดยไม่ตีความ payment state หรือ Batch state',
    irreversible: 'ลบถาวรและ Restore ไม่ได้',
    confirmation: 'ฉันยืนยันว่าเป็น Hard Delete แบบถาวร เข้าใจว่าเมื่อสำเร็จ target row จะถูกลบจริงและจะเหลือเฉพาะ Hard Delete Audit',
    hardDelete: 'Hard Delete',
    submitting: 'กำลังลบถาวร…',
    noSelection: 'โปรดเลือก Hard Delete target ก่อน',
    confirmationRequired: 'ต้องยืนยันคำเตือนการลบถาวรก่อน',
    boundaryHint: 'UI จะไม่คาดเดาว่า target ลบได้หรือไม่ และจะไม่ cascade, detach หรือแก้ประวัติ เมื่อส่งคำสั่ง server จะ lock target, ตรวจ exact row_version และตรวจ typed dependencies ใหม่ ถ้ามี dependency จะปฏิเสธ',
    queryFailed: 'โหลด Hard Delete target options ไม่สำเร็จ',
    invalid: 'Hard Delete request ไม่ถูกต้อง โปรดโหลดใหม่แล้วลองอีกครั้ง',
    notFound: 'ไม่พบ target ที่เลือก โปรดโหลดใหม่',
    dependencyBlocked: 'Hard Delete ถูกบล็อกโดย typed dependency ระบบจะไม่ cascade, detach หรือลบข้อมูลประวัติ',
    stale: 'Row version เปลี่ยนแล้ว โปรดโหลดสถานะล่าสุดก่อนดำเนินการ',
    idempotency: 'Idempotency-Key นี้ถูกใช้กับ request อื่นแล้ว โปรดเริ่มการทำงานใหม่',
    unexpected: 'เกิดข้อผิดพลาดที่ไม่คาดคิด',
    success: 'Hard Delete สำเร็จ',
    deletedTarget: 'Deleted target',
  },
} as const;
