export const hardDeleteCopy = {
  'zh-TW': {
    eyebrow: '資料保護',
    title: '永久刪除資料保護控制',
    intro: '永久刪除僅允許最高刪除權限帳號執行，並且必須先完成登入身分重新驗證。',
    suppliers: '供應商',
    customers: '客戶',
    'outsourced-vendors': '委外供應商',
    farmers: '農戶',
    'procurement-products': '採購產品',
    'sales-products': '銷售產品',
    'sales-product-groups': '銷售產品群組',
    'outsourced-supply-batches': '委外主單',
    'outsourced-supply-details': '委外明細',
    'procurement-batches': '採購主單',
    'procurement-entries': '採購明細',
    sales: '銷售主單',
    'sales-details': '銷售明細',
    'processing-executions': '加工主單',
    'processing-execution-inputs': '加工投入明細',
    'processing-execution-outputs': '加工產出明細',
    search: '搜尋',
    choose: '選擇永久刪除對象',
    loading: '載入中…',
    activeLabel: '啟用狀態',
    active: '啟用',
    inactive: '停用',
    lifecycleState: '資料狀態',
    current: '現行',
    deleted: '已軟刪除',
    rowVersion: '資料版本',
    deletedAt: '刪除時間',
    notDeleted: '—',
    dependencyGate: '資料關聯處理',
    dependencySupplier: '永久刪除會由伺服器在交易內重新檢查資料關聯。',
    dependencyCustomer: '永久刪除會由伺服器在交易內重新檢查資料關聯。',
    dependencyVendor: '永久刪除會由伺服器在交易內重新檢查資料關聯。',
    dependencyFarmer: '永久刪除會由伺服器在交易內重新檢查資料關聯。',
    irreversible: '永久刪除、不可恢復',
    confirmation: '我確認永久刪除。成功後該筆資料會實體刪除，並保留永久刪除稽核紀錄。',
    hardDelete: '永久刪除',
    submitting: '永久刪除中…',
    noSelection: '請先選擇永久刪除對象。',
    confirmationRequired: '必須先確認永久刪除。',
    boundaryHint: '送出後由伺服器鎖定資料、核對資料版本並重新檢查相依資料。',
    queryFailed: '永久刪除對象查詢失敗',
    invalid: '永久刪除資料無效，請重新載入後再操作。',
    notFound: '所選對象已不存在，請重新載入。',
    dependencyBlocked: '仍有資料引用此對象，永久刪除已阻擋；資料未變更。',
    stale: '資料版本已變更，請重新載入最新狀態後再操作。',
    idempotency: '此操作識別碼已被不同請求使用，請重新開始一次操作。',
    reauthRequired: '刪除前必須重新驗證登入身分。',
    unexpected: '發生未預期錯誤。',
    success: '永久刪除已完成',
    deletedTarget: '已刪除對象',
  },
  'th-TH': {
    eyebrow: 'การคุ้มครองข้อมูล',
    title: 'การควบคุมการลบถาวร',
    intro: 'การลบถาวรทำได้เฉพาะบัญชีที่มีสิทธิ์ลบสูงสุด และต้องยืนยันตัวตนในการเข้าสู่ระบบอีกครั้งก่อนดำเนินการ',
    suppliers: 'ผู้จำหน่าย',
    customers: 'ลูกค้า',
    'outsourced-vendors': 'ผู้รับจ้างภายนอก',
    farmers: 'เกษตรกร',
    'procurement-products': 'สินค้าจัดซื้อ',
    'sales-products': 'สินค้าขาย',
    'sales-product-groups': 'กลุ่มสินค้าขาย',
    'outsourced-supply-batches': 'รายการงานภายนอกหลัก',
    'outsourced-supply-details': 'รายละเอียดงานภายนอก',
    'procurement-batches': 'ใบจัดซื้อหลัก',
    'procurement-entries': 'รายละเอียดการจัดซื้อ',
    sales: 'ใบขายหลัก',
    'sales-details': 'รายละเอียดการขาย',
    'processing-executions': 'รายการแปรรูปหลัก',
    'processing-execution-inputs': 'รายละเอียดวัตถุดิบเข้า',
    'processing-execution-outputs': 'รายละเอียดผลผลิต',
    search: 'ค้นหา',
    choose: 'เลือกรายการที่จะลบถาวร',
    loading: 'กำลังโหลด…',
    activeLabel: 'สถานะการใช้งาน',
    active: 'ใช้งาน',
    inactive: 'ไม่ใช้งาน',
    lifecycleState: 'สถานะข้อมูล',
    current: 'ปัจจุบัน',
    deleted: 'ลบแบบเก็บประวัติแล้ว',
    rowVersion: 'รุ่นข้อมูล',
    deletedAt: 'เวลาที่ลบ',
    notDeleted: '—',
    dependencyGate: 'การจัดการความสัมพันธ์ข้อมูล',
    dependencySupplier: 'เซิร์ฟเวอร์จะตรวจสอบความสัมพันธ์ข้อมูลอีกครั้งภายในธุรกรรมก่อนลบถาวร',
    dependencyCustomer: 'เซิร์ฟเวอร์จะตรวจสอบความสัมพันธ์ข้อมูลอีกครั้งภายในธุรกรรมก่อนลบถาวร',
    dependencyVendor: 'เซิร์ฟเวอร์จะตรวจสอบความสัมพันธ์ข้อมูลอีกครั้งภายในธุรกรรมก่อนลบถาวร',
    dependencyFarmer: 'เซิร์ฟเวอร์จะตรวจสอบความสัมพันธ์ข้อมูลอีกครั้งภายในธุรกรรมก่อนลบถาวร',
    irreversible: 'ลบถาวรและกู้คืนไม่ได้',
    confirmation: 'ฉันยืนยันการลบถาวร เมื่อสำเร็จข้อมูลจะถูกลบจริงและคงบันทึกการตรวจสอบการลบถาวรไว้',
    hardDelete: 'ลบถาวร',
    submitting: 'กำลังลบถาวร…',
    noSelection: 'โปรดเลือกรายการที่จะลบถาวร',
    confirmationRequired: 'ต้องยืนยันการลบถาวรก่อน',
    boundaryHint: 'หลังส่งคำสั่ง เซิร์ฟเวอร์จะล็อกข้อมูล ตรวจรุ่นข้อมูล และตรวจสอบข้อมูลที่อ้างอิงอีกครั้ง',
    queryFailed: 'โหลดรายการสำหรับลบถาวรไม่สำเร็จ',
    invalid: 'ข้อมูลการลบถาวรไม่ถูกต้อง โปรดโหลดใหม่แล้วลองอีกครั้ง',
    notFound: 'ไม่พบรายการที่เลือก โปรดโหลดใหม่',
    dependencyBlocked: 'ยังมีข้อมูลอ้างอิงรายการนี้ จึงไม่สามารถลบถาวรได้ และข้อมูลไม่ได้เปลี่ยนแปลง',
    stale: 'รุ่นข้อมูลเปลี่ยนแล้ว โปรดโหลดสถานะล่าสุดก่อนดำเนินการ',
    idempotency: 'รหัสการทำงานนี้ถูกใช้กับคำขออื่นแล้ว โปรดเริ่มการทำงานใหม่',
    reauthRequired: 'ต้องยืนยันตัวตนในการเข้าสู่ระบบอีกครั้งก่อนลบ',
    unexpected: 'เกิดข้อผิดพลาดที่ไม่คาดคิด',
    success: 'ลบถาวรสำเร็จ',
    deletedTarget: 'รายการที่ลบแล้ว',
  },
} as const;
