export const salesProductGroupLifecycleCopy = {
  'zh-TW': {
    eyebrow: 'P7 · 產品設定',
    title: 'Sales Product Group 生命週期控制',
    intro: '此頁只使用已正式確認的 Sales Product Group Soft Delete / Restore commands。Restore 只清除 soft-deleted 狀態，不會自動把 inactive 改為 active，也不會修改任何 child Sales Product。ProcurementProduct 與 SalesProduct lifecycle 仍維持 TO VERIFY / DEFERRED。',
    search: '搜尋群組名稱',
    choose: '選擇 Sales Product Group',
    loading: '載入中…',
    activeLabel: 'Active state',
    active: 'Active',
    inactive: 'Inactive',
    lifecycleState: 'Lifecycle state',
    current: 'Current',
    deleted: 'Soft deleted',
    rowVersion: 'Row version',
    deletedAt: 'Deleted at',
    notDeleted: '—',
    softDelete: 'Soft Delete',
    restore: 'Restore',
    submitting: '處理中…',
    noSelection: '請先選擇一筆 Sales Product Group。',
    boundaryHint: 'Group lifecycle 不會 cascade 到 Sales Products，不會改寫 Sales、Processing、Inventory 或其他歷史資料；未確認的 ProcurementProduct / SalesProduct lifecycle 不在此頁提供。',
    queryFailed: 'Sales Product Group lifecycle options 查詢失敗',
    invalid: 'Lifecycle request 無效，請重新載入後再操作。',
    notFound: '所選 Sales Product Group 已不存在，請重新載入。',
    alreadyDeleted: '此 Sales Product Group 已是 Soft Deleted 狀態，請重新載入。',
    notDeletedState: '此 Sales Product Group 目前不是 Soft Deleted 狀態，請重新載入。',
    stale: 'Row version 已變更，請重新載入最新狀態後再操作。',
    idempotency: '此 Idempotency-Key 已被不同 request 使用，請重新開始一次操作。',
    unexpected: '發生未預期錯誤。',
    successDelete: 'Soft Delete 已完成',
    successRestore: 'Restore 已完成',
    newRowVersion: 'New row version',
  },
  'th-TH': {
    eyebrow: 'P7 · การตั้งค่าสินค้า',
    title: 'ควบคุมวงจรชีวิต Sales Product Group',
    intro: 'หน้านี้ใช้เฉพาะคำสั่ง Soft Delete / Restore ของ Sales Product Group ที่ยืนยันแล้ว Restore จะล้างเฉพาะสถานะ soft-deleted และจะไม่เปลี่ยน inactive เป็น active โดยอัตโนมัติ รวมทั้งไม่แก้ไข Sales Product ลูก ส่วน lifecycle ของ ProcurementProduct และ SalesProduct ยังคงเป็น TO VERIFY / DEFERRED',
    search: 'ค้นหาชื่อกลุ่ม',
    choose: 'เลือก Sales Product Group',
    loading: 'กำลังโหลด…',
    activeLabel: 'Active state',
    active: 'Active',
    inactive: 'Inactive',
    lifecycleState: 'Lifecycle state',
    current: 'Current',
    deleted: 'Soft deleted',
    rowVersion: 'Row version',
    deletedAt: 'Deleted at',
    notDeleted: '—',
    softDelete: 'Soft Delete',
    restore: 'Restore',
    submitting: 'กำลังดำเนินการ…',
    noSelection: 'โปรดเลือก Sales Product Group ก่อน',
    boundaryHint: 'lifecycle ของ Group จะไม่ cascade ไปยัง Sales Product และจะไม่แก้ประวัติ Sales, Processing, Inventory หรือข้อมูลย้อนหลังอื่น ๆ ส่วน ProcurementProduct / SalesProduct lifecycle ที่ยังไม่ยืนยันจะไม่ปรากฏในหน้านี้',
    queryFailed: 'โหลด Sales Product Group lifecycle options ไม่สำเร็จ',
    invalid: 'Lifecycle request ไม่ถูกต้อง โปรดโหลดใหม่แล้วลองอีกครั้ง',
    notFound: 'ไม่พบ Sales Product Group ที่เลือก โปรดโหลดใหม่',
    alreadyDeleted: 'Sales Product Group นี้เป็น Soft Deleted อยู่แล้ว โปรดโหลดใหม่',
    notDeletedState: 'Sales Product Group นี้ไม่ได้อยู่ในสถานะ Soft Deleted โปรดโหลดใหม่',
    stale: 'Row version เปลี่ยนแล้ว โปรดโหลดสถานะล่าสุดก่อนดำเนินการ',
    idempotency: 'Idempotency-Key นี้ถูกใช้กับ request อื่นแล้ว โปรดเริ่มการทำงานใหม่',
    unexpected: 'เกิดข้อผิดพลาดที่ไม่คาดคิด',
    successDelete: 'Soft Delete สำเร็จ',
    successRestore: 'Restore สำเร็จ',
    newRowVersion: 'New row version',
  },
} as const;
