export const salesProductGroupLifecycleCopy = {
  'zh-TW': {
    eyebrow: 'P7 · 產品設定',
    title: '銷售產品群組生命週期控制',
    entityLabel: '銷售產品群組',
    intro: '此頁只使用已正式確認的銷售產品群組軟刪除／恢復操作。恢復只清除軟刪除狀態，不會自動把停用改為啟用，也不會修改子產品。',
    search: '搜尋群組名稱',
    choose: '選擇銷售產品群組',
    loading: '載入中…',
    activeLabel: '啟用狀態',
    active: '啟用',
    inactive: '停用',
    lifecycleState: '資料狀態',
    current: '現行',
    deleted: '已軟刪除',
    rowVersion: '資料版本',
    deletedAt: '刪除時間',
    notDeleted: '—',
    softDelete: '軟刪除',
    restore: '恢復',
    submitting: '處理中…',
    noSelection: '請先選擇一筆銷售產品群組。',
    boundaryHint: '群組生命週期不會連動子產品，也不會改寫歷史資料。',
    queryFailed: '銷售產品群組選項查詢失敗',
    invalid: '操作資料無效，請重新載入後再操作。',
    notFound: '所選銷售產品群組已不存在，請重新載入。',
    alreadyDeleted: '此銷售產品群組已是軟刪除狀態，請重新載入。',
    notDeletedState: '此銷售產品群組目前不是軟刪除狀態，請重新載入。',
    stale: '資料版本已變更，請重新載入最新狀態後再操作。',
    idempotency: '此操作識別碼已被不同請求使用，請重新開始一次操作。',
    unexpected: '發生未預期錯誤。',
    successDelete: '軟刪除已完成',
    successRestore: '恢復已完成',
    newRowVersion: '新資料版本',
  },
  'th-TH': {
    eyebrow: 'P7 · การตั้งค่าสินค้า',
    title: 'ควบคุมวงจรข้อมูลกลุ่มสินค้าขาย',
    entityLabel: 'กลุ่มสินค้าขาย',
    intro: 'หน้านี้ใช้เฉพาะการลบแบบเก็บประวัติและการกู้คืนของกลุ่มสินค้าขายที่ยืนยันแล้ว การกู้คืนจะล้างเฉพาะสถานะลบ และจะไม่เปิดใช้งานรายการที่ถูกปิดโดยอัตโนมัติหรือแก้ข้อมูลสินค้าลูก',
    search: 'ค้นหาชื่อกลุ่ม',
    choose: 'เลือกกลุ่มสินค้าขาย',
    loading: 'กำลังโหลด…',
    activeLabel: 'สถานะการใช้งาน',
    active: 'ใช้งาน',
    inactive: 'ไม่ใช้งาน',
    lifecycleState: 'สถานะข้อมูล',
    current: 'ปัจจุบัน',
    deleted: 'ลบแบบเก็บประวัติแล้ว',
    rowVersion: 'รุ่นข้อมูล',
    deletedAt: 'เวลาที่ลบ',
    notDeleted: '—',
    softDelete: 'ลบแบบเก็บประวัติ',
    restore: 'กู้คืน',
    submitting: 'กำลังดำเนินการ…',
    noSelection: 'โปรดเลือกกลุ่มสินค้าขายก่อน',
    boundaryHint: 'สถานะของกลุ่มจะไม่เปลี่ยนสถานะสินค้าลูก และจะไม่แก้ข้อมูลประวัติย้อนหลัง',
    queryFailed: 'โหลดตัวเลือกกลุ่มสินค้าขายไม่สำเร็จ',
    invalid: 'ข้อมูลการทำงานไม่ถูกต้อง โปรดโหลดใหม่แล้วลองอีกครั้ง',
    notFound: 'ไม่พบกลุ่มสินค้าขายที่เลือก โปรดโหลดใหม่',
    alreadyDeleted: 'กลุ่มสินค้าขายนี้ถูกลบแบบเก็บประวัติแล้ว โปรดโหลดใหม่',
    notDeletedState: 'กลุ่มสินค้าขายนี้ยังไม่ได้ถูกลบแบบเก็บประวัติ โปรดโหลดใหม่',
    stale: 'รุ่นข้อมูลเปลี่ยนแล้ว โปรดโหลดสถานะล่าสุดก่อนดำเนินการ',
    idempotency: 'รหัสการทำงานนี้ถูกใช้กับคำขออื่นแล้ว โปรดเริ่มการทำงานใหม่',
    unexpected: 'เกิดข้อผิดพลาดที่ไม่คาดคิด',
    successDelete: 'ลบแบบเก็บประวัติสำเร็จ',
    successRestore: 'กู้คืนสำเร็จ',
    newRowVersion: 'รุ่นข้อมูลใหม่',
  },
} as const;
