<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>YowThi.Erp.Infrastructure.Migrations</RootNamespace>
    <AssemblyName>YowThi.Erp.Infrastructure.Migrations</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../YowThi.Erp.Infrastructure/YowThi.Erp.Infrastructure.csproj" />
  </ItemGroup>
</Project>
