export const partyLifecycleCopy = {
  'zh-TW': {
    eyebrow: 'P7 · 人員與往來對象',
    title: '人員與往來對象主檔控制',
    intro: '此頁使用既有主檔軟刪除／恢復操作。軟刪除保留歷史關聯與稽核；恢復只清除軟刪除狀態，不會自動重新啟用停用主檔。',
    suppliers: '供應商',
    customers: '客戶',
    outsourcedVendors: '委外供應商',
    farmers: '農戶',
    employees: '員工',
    search: '搜尋名稱',
    choose: '選擇主檔',
    loading: '載入中…',
    active: '啟用',
    inactive: '停用',
    current: '現行',
    deleted: '已軟刪除',
    rowVersion: '資料版本',
    deletedAt: '刪除時間',
    notDeleted: '—',
    softDelete: '軟刪除',
    restore: '恢復',
    submitting: '處理中…',
    noSelection: '請先選擇一筆主檔。',
    lifecycleHint: '生命週期操作不會改寫既有歷史資料；恢復也不會自動重新啟用停用主檔。',
    queryFailed: '主檔選項查詢失敗',
    invalid: '操作資料無效，請重新載入後再操作。',
    notFound: '所選主檔已不存在，請重新載入。',
    alreadyDeleted: '此主檔已是軟刪除狀態，請重新載入。',
    notDeletedState: '此主檔目前不是軟刪除狀態，請重新載入。',
    stale: '資料版本已變更，請重新載入最新狀態後再操作。',
    idempotency: '此操作識別碼已被不同請求使用，請重新開始一次操作。',
    unexpected: '發生未預期錯誤。',
    successDelete: '軟刪除已完成',
    successRestore: '恢復已完成',
    resultState: '資料狀態',
    resultRowVersion: '新資料版本',
  },
  'th-TH': {
    eyebrow: 'P7 · บุคลากรและคู่ค้า',
    title: 'ควบคุมข้อมูลหลักบุคลากรและคู่ค้า',
    intro: 'หน้านี้ใช้การลบแบบเก็บประวัติและการกู้คืนของข้อมูลหลักที่มีอยู่ การลบยังคงความสัมพันธ์และบันทึกตรวจสอบ ส่วนการกู้คืนจะไม่เปิดใช้งานข้อมูลที่ถูกปิดใช้งานโดยอัตโนมัติ',
    suppliers: 'ผู้จำหน่าย',
    customers: 'ลูกค้า',
    outsourcedVendors: 'ผู้รับจ้างภายนอก',
    farmers: 'เกษตรกร',
    employees: 'พนักงาน',
    search: 'ค้นหาชื่อ',
    choose: 'เลือกข้อมูลหลัก',
    loading: 'กำลังโหลด…',
    active: 'ใช้งาน',
    inactive: 'ไม่ใช้งาน',
    current: 'ปัจจุบัน',
    deleted: 'ลบแบบเก็บประวัติแล้ว',
    rowVersion: 'รุ่นข้อมูล',
    deletedAt: 'เวลาที่ลบ',
    notDeleted: '—',
    softDelete: 'ลบแบบเก็บประวัติ',
    restore: 'กู้คืน',
    submitting: 'กำลังดำเนินการ…',
    noSelection: 'โปรดเลือกข้อมูลหลักก่อน',
    lifecycleHint: 'การเปลี่ยนสถานะข้อมูลจะไม่แก้ประวัติเดิม และการกู้คืนจะไม่เปิดใช้งานข้อมูลที่ถูกปิดใช้งานโดยอัตโนมัติ',
    queryFailed: 'โหลดตัวเลือกข้อมูลหลักไม่สำเร็จ',
    invalid: 'ข้อมูลการทำงานไม่ถูกต้อง โปรดโหลดใหม่แล้วลองอีกครั้ง',
    notFound: 'ไม่พบข้อมูลหลักที่เลือก โปรดโหลดใหม่',
    alreadyDeleted: 'ข้อมูลหลักนี้ถูกลบแบบเก็บประวัติแล้ว โปรดโหลดใหม่',
    notDeletedState: 'ข้อมูลหลักนี้ยังไม่ได้ถูกลบแบบเก็บประวัติ โปรดโหลดใหม่',
    stale: 'รุ่นข้อมูลเปลี่ยนแล้ว โปรดโหลดสถานะล่าสุดก่อนดำเนินการ',
    idempotency: 'รหัสการทำงานนี้ถูกใช้กับคำขออื่นแล้ว โปรดเริ่มการทำงานใหม่',
    unexpected: 'เกิดข้อผิดพลาดที่ไม่คาดคิด',
    successDelete: 'ลบแบบเก็บประวัติสำเร็จ',
    successRestore: 'กู้คืนสำเร็จ',
    resultState: 'สถานะข้อมูล',
    resultRowVersion: 'รุ่นข้อมูลใหม่',
  },
} as const;
