export const partyLifecycleCopy = {
  'zh-TW': {
    eyebrow: 'P7 · 人員與往來對象',
    title: 'Party 主檔生命週期控制',
    intro: '此頁直接使用既有 target-specific Soft Delete / Restore commands。Soft Delete 保留歷史 FK 與 Audit；Restore 只清除 soft-deleted 狀態，不會自動把 active 改為 true。Hard Delete 屬於 Data Protection 高權限控制，不在此頁。',
    suppliers: '供應商',
    customers: '客戶',
    outsourcedVendors: '委外供應商',
    farmers: '農戶',
    employees: '員工',
    search: '搜尋名稱',
    choose: '選擇主檔',
    loading: '載入中…',
    active: 'Active',
    inactive: 'Inactive',
    current: 'Current',
    deleted: 'Soft deleted',
    rowVersion: 'Row version',
    deletedAt: 'Deleted at',
    notDeleted: '—',
    softDelete: 'Soft Delete',
    restore: 'Restore',
    submitting: '處理中…',
    noSelection: '請先選擇一筆 Party 主檔。',
    lifecycleHint: 'Lifecycle 操作不會改寫既有採購、銷售、加工、工資、庫存或財務歷史；Restore 也不會自動重新啟用 inactive 主檔。',
    queryFailed: 'Party lifecycle options 查詢失敗',
    invalid: 'Lifecycle request 無效，請重新載入後再操作。',
    notFound: '所選主檔已不存在，請重新載入。',
    alreadyDeleted: '此主檔已是 Soft Deleted 狀態，請重新載入。',
    notDeletedState: '此主檔目前不是 Soft Deleted 狀態，請重新載入。',
    stale: 'Row version 已變更，請重新載入最新狀態後再操作。',
    idempotency: '此 Idempotency-Key 已被不同 request 使用，請重新開始一次操作。',
    unexpected: '發生未預期錯誤。',
    successDelete: 'Soft Delete 已完成',
    successRestore: 'Restore 已完成',
    resultState: 'Lifecycle state',
    resultRowVersion: 'New row version',
  },
  'th-TH': {
    eyebrow: 'P7 · บุคลากรและคู่ค้า',
    title: 'ควบคุมวงจรชีวิต Party master',
    intro: 'หน้านี้ใช้คำสั่ง Soft Delete / Restore แบบ target-specific ที่มีอยู่จริง Soft Delete ยังคง FK ประวัติและ Audit ส่วน Restore เพียงล้างสถานะ soft-deleted และจะไม่เปลี่ยน active เป็น true โดยอัตโนมัติ Hard Delete เป็นสิทธิ์ระดับ Data Protection และไม่อยู่ในหน้านี้',
    suppliers: 'ซัพพลายเออร์',
    customers: 'ลูกค้า',
    outsourcedVendors: 'ผู้รับจ้างภายนอก',
    farmers: 'เกษตรกร',
    employees: 'พนักงาน',
    search: 'ค้นหาชื่อ',
    choose: 'เลือก master',
    loading: 'กำลังโหลด…',
    active: 'Active',
    inactive: 'Inactive',
    current: 'Current',
    deleted: 'Soft deleted',
    rowVersion: 'Row version',
    deletedAt: 'Deleted at',
    notDeleted: '—',
    softDelete: 'Soft Delete',
    restore: 'Restore',
    submitting: 'กำลังดำเนินการ…',
    noSelection: 'โปรดเลือก Party master ก่อน',
    lifecycleHint: 'การเปลี่ยน lifecycle จะไม่แก้ประวัติการจัดซื้อ การขาย การแปรรูป ค่าแรง สินค้าคงคลัง หรือการเงิน และ Restore จะไม่เปิดใช้ master ที่ inactive โดยอัตโนมัติ',
    queryFailed: 'โหลด Party lifecycle options ไม่สำเร็จ',
    invalid: 'Lifecycle request ไม่ถูกต้อง โปรดโหลดใหม่แล้วลองอีกครั้ง',
    notFound: 'ไม่พบ master ที่เลือก โปรดโหลดใหม่',
    alreadyDeleted: 'master นี้เป็น Soft Deleted อยู่แล้ว โปรดโหลดใหม่',
    notDeletedState: 'master นี้ไม่ได้อยู่ในสถานะ Soft Deleted โปรดโหลดใหม่',
    stale: 'Row version เปลี่ยนแล้ว โปรดโหลดสถานะล่าสุดก่อนดำเนินการ',
    idempotency: 'Idempotency-Key นี้ถูกใช้กับ request อื่นแล้ว โปรดเริ่มการทำงานใหม่',
    unexpected: 'เกิดข้อผิดพลาดที่ไม่คาดคิด',
    successDelete: 'Soft Delete สำเร็จ',
    successRestore: 'Restore สำเร็จ',
    resultState: 'Lifecycle state',
    resultRowVersion: 'New row version',
  },
} as const;
