export const infrastructureLifecycleCopy = {
  'zh-TW': {
    eyebrow: 'P7 · 基礎設施資料',
    title: '容器／倉庫生命週期控制',
    intro: '此頁使用既有容器與倉庫的軟刪除／恢復操作。恢復只清除軟刪除狀態，不會自動把停用改為啟用；倉庫生命週期不會連動子儲位。',
    containers: '容器',
    warehouses: '倉庫',
    search: '搜尋名稱或代碼',
    choose: '選擇主檔',
    loading: '載入中…',
    activeLabel: '啟用狀態',
    active: '啟用',
    inactive: '停用',
    lifecycleState: '資料狀態',
    current: '現行',
    deleted: '已軟刪除',
    rowVersion: '資料版本',
    deletedAt: '刪除時間',
    notDeleted: '—',
    tareWeight: '皮重',
    warehouseCode: '倉庫代碼',
    noCode: '—',
    softDelete: '軟刪除',
    restore: '恢復',
    submitting: '處理中…',
    noSelection: '請先選擇一筆基礎設施主檔。',
    boundaryHint: '容器生命週期不改寫已完成加工的皮重快照；倉庫生命週期不會自動停用、刪除或恢復子儲位，也不改寫歷史資料。',
    queryFailed: '基礎設施選項查詢失敗',
    invalid: '操作資料無效，請重新載入後再操作。',
    notFound: '所選主檔已不存在，請重新載入。',
    alreadyDeleted: '此主檔已是軟刪除狀態，請重新載入。',
    notDeletedState: '此主檔目前不是軟刪除狀態，請重新載入。',
    stale: '資料版本已變更，請重新載入最新狀態後再操作。',
    idempotency: '此操作識別碼已被不同請求使用，請重新開始一次操作。',
    unexpected: '發生未預期錯誤。',
    successDelete: '軟刪除已完成',
    successRestore: '恢復已完成',
    newRowVersion: '新資料版本',
  },
  'th-TH': {
    eyebrow: 'P7 · ข้อมูลโครงสร้างพื้นฐาน',
    title: 'ควบคุมวงจรข้อมูลภาชนะ / คลังสินค้า',
    intro: 'หน้านี้ใช้การลบแบบเก็บประวัติและการกู้คืนของภาชนะกับคลังสินค้าที่มีอยู่ การกู้คืนจะล้างเฉพาะสถานะลบและจะไม่เปลี่ยนรายการที่ไม่ใช้งานให้กลับมาใช้งานโดยอัตโนมัติ',
    containers: 'ภาชนะ',
    warehouses: 'คลังสินค้า',
    search: 'ค้นหาชื่อหรือรหัส',
    choose: 'เลือกข้อมูลหลัก',
    loading: 'กำลังโหลด…',
    activeLabel: 'สถานะการใช้งาน',
    active: 'ใช้งาน',
    inactive: 'ไม่ใช้งาน',
    lifecycleState: 'สถานะข้อมูล',
    current: 'ปัจจุบัน',
    deleted: 'ลบแบบเก็บประวัติแล้ว',
    rowVersion: 'รุ่นข้อมูล',
    deletedAt: 'เวลาที่ลบ',
    notDeleted: '—',
    tareWeight: 'น้ำหนักภาชนะเปล่า',
    warehouseCode: 'รหัสคลังสินค้า',
    noCode: '—',
    softDelete: 'ลบแบบเก็บประวัติ',
    restore: 'กู้คืน',
    submitting: 'กำลังดำเนินการ…',
    noSelection: 'โปรดเลือกข้อมูลหลักก่อน',
    boundaryHint: 'วงจรข้อมูลภาชนะจะไม่แก้ข้อมูลน้ำหนักที่บันทึกจากงานแปรรูป และวงจรข้อมูลคลังสินค้าจะไม่ปิดใช้งาน ลบ หรือกู้คืนตำแหน่งจัดเก็บลูกโดยอัตโนมัติ',
    queryFailed: 'โหลดตัวเลือกโครงสร้างพื้นฐานไม่สำเร็จ',
    invalid: 'ข้อมูลการทำงานไม่ถูกต้อง โปรดโหลดใหม่แล้วลองอีกครั้ง',
    notFound: 'ไม่พบข้อมูลหลักที่เลือก โปรดโหลดใหม่',
    alreadyDeleted: 'ข้อมูลหลักนี้ถูกลบแบบเก็บประวัติแล้ว โปรดโหลดใหม่',
    notDeletedState: 'ข้อมูลหลักนี้ยังไม่ได้ถูกลบแบบเก็บประวัติ โปรดโหลดใหม่',
    stale: 'รุ่นข้อมูลเปลี่ยนแล้ว โปรดโหลดสถานะล่าสุดก่อนดำเนินการ',
    idempotency: 'รหัสการทำงานนี้ถูกใช้กับคำขออื่นแล้ว โปรดเริ่มใหม่',
    unexpected: 'เกิดข้อผิดพลาดที่ไม่คาดคิด',
    successDelete: 'ลบแบบเก็บประวัติสำเร็จ',
    successRestore: 'กู้คืนสำเร็จ',
    newRowVersion: 'รุ่นข้อมูลใหม่',
  },
} as const;
