export const infrastructureLifecycleCopy = {
  'zh-TW': {
    eyebrow: 'P7 · 基礎設施資料',
    title: 'Container / Warehouse 生命週期控制',
    intro: '此頁直接使用既有 Container 與 Warehouse target-specific Soft Delete / Restore commands。Restore 只清除 soft-deleted 狀態，不會自動把 inactive 改為 active。Warehouse lifecycle 不會 cascade 到 child Storage Locations；StorageLocation lifecycle 仍維持 DEFERRED。',
    containers: 'Container',
    warehouses: 'Warehouse',
    search: '搜尋名稱或代碼',
    choose: '選擇主檔',
    loading: '載入中…',
    activeLabel: 'Active state',
    active: 'Active',
    inactive: 'Inactive',
    lifecycleState: 'Lifecycle state',
    current: 'Current',
    deleted: 'Soft deleted',
    rowVersion: 'Row version',
    deletedAt: 'Deleted at',
    notDeleted: '—',
    tareWeight: 'Tare weight',
    warehouseCode: 'Warehouse code',
    noCode: '—',
    softDelete: 'Soft Delete',
    restore: 'Restore',
    submitting: '處理中…',
    noSelection: '請先選擇一筆 Infrastructure 主檔。',
    boundaryHint: 'Container lifecycle 不改寫已完成 Processing tare snapshot。Warehouse lifecycle 不會自動停用、刪除或恢復 child Storage Locations，也不會改寫 Inventory / Sales / Processing 歷史。',
    queryFailed: 'Infrastructure lifecycle options 查詢失敗',
    invalid: 'Lifecycle request 無效，請重新載入後再操作。',
    notFound: '所選主檔已不存在，請重新載入。',
    alreadyDeleted: '此主檔已是 Soft Deleted 狀態，請重新載入。',
    notDeletedState: '此主檔目前不是 Soft Deleted 狀態，請重新載入。',
    stale: 'Row version 已變更，請重新載入最新狀態後再操作。',
    idempotency: '此 Idempotency-Key 已被不同 request 使用，請重新開始一次操作。',
    unexpected: '發生未預期錯誤。',
    successDelete: 'Soft Delete 已完成',
    successRestore: 'Restore 已完成',
    newRowVersion: 'New row version',
  },
  'th-TH': {
    eyebrow: 'P7 · ข้อมูลโครงสร้างพื้นฐาน',
    title: 'ควบคุมวงจรชีวิต Container / Warehouse',
    intro: 'หน้านี้ใช้คำสั่ง Soft Delete / Restore แบบ target-specific ของ Container และ Warehouse ที่มีอยู่จริง Restore จะล้างเฉพาะสถานะ soft-deleted และจะไม่เปลี่ยน inactive เป็น active โดยอัตโนมัติ lifecycle ของ Warehouse จะไม่ cascade ไปยัง Storage Location ลูก และ lifecycle ของ StorageLocation ยังเป็น DEFERRED',
    containers: 'Container',
    warehouses: 'Warehouse',
    search: 'ค้นหาชื่อหรือรหัส',
    choose: 'เลือก master',
    loading: 'กำลังโหลด…',
    activeLabel: 'Active state',
    active: 'Active',
    inactive: 'Inactive',
    lifecycleState: 'Lifecycle state',
    current: 'Current',
    deleted: 'Soft deleted',
    rowVersion: 'Row version',
    deletedAt: 'Deleted at',
    notDeleted: '—',
    tareWeight: 'Tare weight',
    warehouseCode: 'Warehouse code',
    noCode: '—',
    softDelete: 'Soft Delete',
    restore: 'Restore',
    submitting: 'กำลังดำเนินการ…',
    noSelection: 'โปรดเลือก Infrastructure master ก่อน',
    boundaryHint: 'lifecycle ของ Container จะไม่แก้ Processing tare snapshot ที่บันทึกแล้ว lifecycle ของ Warehouse จะไม่ปิดใช้งาน ลบ หรือ Restore Storage Location ลูกโดยอัตโนมัติ และจะไม่แก้ประวัติ Inventory / Sales / Processing',
    queryFailed: 'โหลด Infrastructure lifecycle options ไม่สำเร็จ',
    invalid: 'Lifecycle request ไม่ถูกต้อง โปรดโหลดใหม่แล้วลองอีกครั้ง',
    notFound: 'ไม่พบ master ที่เลือก โปรดโหลดใหม่',
    alreadyDeleted: 'master นี้เป็น Soft Deleted อยู่แล้ว โปรดโหลดใหม่',
    notDeletedState: 'master นี้ไม่ได้อยู่ในสถานะ Soft Deleted โปรดโหลดใหม่',
    stale: 'Row version เปลี่ยนแล้ว โปรดโหลดสถานะล่าสุดก่อนดำเนินการ',
    idempotency: 'Idempotency-Key นี้ถูกใช้กับ request อื่นแล้ว โปรดเริ่มใหม่',
    unexpected: 'เกิดข้อผิดพลาดที่ไม่คาดคิด',
    successDelete: 'Soft Delete สำเร็จ',
    successRestore: 'Restore สำเร็จ',
    newRowVersion: 'New row version',
  },
} as const;
